-------------------------------------------------------------------------------
Test set: org.apache.ratis.grpc.TestServerRestartWithGrpc
-------------------------------------------------------------------------------
Tests run: 6, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 105.907 s <<< FAILURE! - in org.apache.ratis.grpc.TestServerRestartWithGrpc
testRestartFollower(org.apache.ratis.grpc.TestServerRestartWithGrpc)  Time elapsed: 100.01 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 100 seconds
	at java.base@11.0.18/java.lang.Object.wait(Native Method)
	at java.base@11.0.18/java.lang.Object.wait(Object.java:328)
	at app//org.apache.ratis.thirdparty.io.grpc.internal.ServerImpl.awaitTermination(ServerImpl.java:320)
	at app//org.apache.ratis.grpc.server.GrpcService.closeImpl(GrpcService.java:315)
	at app//org.apache.ratis.server.RaftServerRpcWithProxy$$Lambda$626/0x00000001003f9c40.run(Unknown Source)
	at app//org.apache.ratis.util.LifeCycle.lambda$checkStateAndClose$4(LifeCycle.java:299)
	at app//org.apache.ratis.util.LifeCycle$$Lambda$447/0x0000000100313040.get(Unknown Source)
	at app//org.apache.ratis.util.LifeCycle.checkStateAndClose(LifeCycle.java:319)
	at app//org.apache.ratis.util.LifeCycle.checkStateAndClose(LifeCycle.java:297)
	at app//org.apache.ratis.server.RaftServerRpcWithProxy.close(RaftServerRpcWithProxy.java:80)
	at app//org.apache.ratis.server.impl.RaftServerProxy.lambda$close$7(RaftServerProxy.java:416)
	at app//org.apache.ratis.server.impl.RaftServerProxy$$Lambda$624/0x00000001003f9440.run(Unknown Source)
	at app//org.apache.ratis.util.LifeCycle.lambda$checkStateAndClose$4(LifeCycle.java:299)
	at app//org.apache.ratis.util.LifeCycle$$Lambda$447/0x0000000100313040.get(Unknown Source)
	at app//org.apache.ratis.util.LifeCycle.checkStateAndClose(LifeCycle.java:319)
	at app//org.apache.ratis.util.LifeCycle.checkStateAndClose(LifeCycle.java:297)
	at app//org.apache.ratis.server.impl.RaftServerProxy.close(RaftServerProxy.java:411)
	at app//org.apache.ratis.server.ServerRestartTests.runTestRestartFollower(ServerRestartTests.java:128)
	at app//org.apache.ratis.server.ServerRestartTests$$Lambda$808/0x0000000100482c40.accept(Unknown Source)
	at app//org.apache.ratis.server.impl.MiniRaftCluster$Factory$Get.runWithNewCluster(MiniRaftCluster.java:141)
	at app//org.apache.ratis.server.impl.MiniRaftCluster$Factory$Get.runWithNewCluster(MiniRaftCluster.java:121)
	at app//org.apache.ratis.server.ServerRestartTests.testRestartFollower(ServerRestartTests.java:88)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.18/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.18/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.18/java.lang.Thread.run(Thread.java:829)

testRestartWithCorruptedLogEntryWithException(org.apache.ratis.grpc.TestServerRestartWithGrpc)  Time elapsed: 0.987 s  <<< FAILURE!
java.lang.AssertionError: expected:<class java.util.concurrent.CompletionException> but was:<class java.lang.AssertionError>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.apache.ratis.BaseTest.assertThrowable(BaseTest.java:135)
	at org.apache.ratis.BaseTest.testFailureCase(BaseTest.java:156)
	at org.apache.ratis.BaseTest.testFailureCase(BaseTest.java:167)
	at org.apache.ratis.server.ServerRestartTests.testRestartWithCorruptedLogEntryWithException(ServerRestartTests.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

testRestartWithCorruptedLogEntryWithException(org.apache.ratis.grpc.TestServerRestartWithGrpc)  Time elapsed: 0.989 s  <<< FAILURE!
java.lang.AssertionError: Unexpected exit.
	at org.apache.ratis.util.ExitUtils.assertNotTerminated(ExitUtils.java:109)
	at org.apache.ratis.BaseTest.assertNoFailures(BaseTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.ratis.util.ExitUtils$ExitException: Failed to start Grpc server
	at org.apache.ratis.util.ExitUtils.terminate(ExitUtils.java:141)
	at org.apache.ratis.util.ExitUtils.terminate(ExitUtils.java:151)
	at org.apache.ratis.grpc.server.GrpcService.startImpl(GrpcService.java:300)
	at org.apache.ratis.util.LifeCycle.startAndTransition(LifeCycle.java:270)
	at org.apache.ratis.server.RaftServerRpcWithProxy.start(RaftServerRpcWithProxy.java:72)
	at org.apache.ratis.server.impl.RaftServerProxy.startImpl(RaftServerProxy.java:397)
	at org.apache.ratis.util.LifeCycle.startAndTransition(LifeCycle.java:270)
	at org.apache.ratis.server.impl.RaftServerProxy.start(RaftServerProxy.java:390)
	at org.apache.ratis.server.impl.MiniRaftCluster.restartServer(MiniRaftCluster.java:364)
	at org.apache.ratis.server.impl.MiniRaftCluster.restartServer(MiniRaftCluster.java:356)
	at org.apache.ratis.server.ServerRestartTests.assertTruncatedLog(ServerRestartTests.java:167)
	at org.apache.ratis.server.ServerRestartTests.runTestRestartFollower(ServerRestartTests.java:132)
	at org.apache.ratis.server.impl.MiniRaftCluster$Factory$Get.runWithNewCluster(MiniRaftCluster.java:141)
	at org.apache.ratis.server.impl.MiniRaftCluster$Factory$Get.runWithNewCluster(MiniRaftCluster.java:121)
	at org.apache.ratis.server.ServerRestartTests.testRestartFollower(ServerRestartTests.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	... 4 more
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:39689
	at org.apache.ratis.thirdparty.io.grpc.netty.NettyServer.start(NettyServer.java:328)
	at org.apache.ratis.thirdparty.io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
	at org.apache.ratis.thirdparty.io.grpc.internal.ServerImpl.start(ServerImpl.java:92)
	at org.apache.ratis.grpc.server.GrpcService.startImpl(GrpcService.java:298)
	... 25 more
Caused by: org.apache.ratis.thirdparty.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

